### ISSUE TITLE
Implement SourceLiveTimer Parsing

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [CryZe/livesplit-core#105]
Seems to be valid to me, but ends up being accepted as a valid urn file which causes errors.  Zipped because github won't let you upload json files.

[test.json.zip](https://github.com/CryZe/livesplit-core/files/1722379/test.json.zip)

**Comment by BatedUrGonnaDie** [comment]
Another one for you.
[test2.json.zip](https://github.com/CryZe/livesplit-core/files/1722424/test2.json.zip)

**Comment by hallcristobal** [comment]
What do you mean by "causes errors", parsing incorrectly?

**Comment by CryZe** [comment]
They changed their file format completely it seems (scuffed CSV to JSON). So we'll probably have to download their current version (Portal 2 Live Timer is the timer) and just see how it works now.

**Comment by hallcristobal** [comment]
Could you provide a link to the timer used @BatedUrGonnaDie ?

**Comment by CryZe** [comment]
it's a file that got uploaded to splits.io. He doesn't know where it came from.

**Comment by hallcristobal** [comment]
oh

**Comment by BatedUrGonnaDie** [comment]
What he said.  Was trying to figure out why a bunch of files had no segments at all and just testing files that had been uploaded.
