### ISSUE TITLE
Build error "livesplit_core_capi matched no packages"

### ISSUE THREAD

**Issue by glacials** [CryZe/livesplit-core#23]
I'm trying to build using the instructions in the README and I get this output:
```sh
$ cargo build --release -p livesplit_core_capi
error: package id specification `livesplit_core_capi` matched no packages
```

Version info if it helps (macOS 10.12.3):
```sh
$ cargo --version
cargo-0.17.0-dev (f9e5481 2017-03-03)
$ rustc --version
rustc 1.16.0
```

**Comment by CryZe** [comment]
Welp, next time I should verify that my instructions are actually correct. It should be `cargo build --release -p livesplit-core-capi` instead. There's builds available though, so you don't actually need to build it yourself.
