### ISSUE TITLE
Possible segfault in urn parser

### ISSUE THREAD

**Issue by Kipples** [CryZe/livesplit-core#56]
Any urn file I try and parse segfaults if it is missing the 'start_delay' key in the json.
I can't really determine if this is a bug in ls-core or from something else, I had issues with both emscripten and a basic C program.

The urn spec says that all keys are optional so not having 'start_delay' shouldn't error.

I don't have any issues loading the same file in the actual urn application.

**Comment by CryZe** [comment]
Yeah, looks like I require that to be a valid number at the moment. In both the JS API and the C API null is returned when it can't parse the splits. Is that not what happened? It definitely shouldn't ever segfault (unless you didn't habdle the null and straight up worked with the null value, in which case it will segfault).

**Comment by CryZe** [comment]
Alright, I pushed a fix, so all the keys can be optional, which seems to be the case for Urn's format. Let me know if it works now, and if it actually was a segfault (see last comment).

**Comment by Kipples** [comment]
Thanks, this has fixed my issue looks like urn will strip start_delay out if its 0 when you save so this makes it easier for me.

You are correct regarding the segfault the basic C program had no null checks I was just passing parse straight into the timer constructor. (I copy pasted code from here [https://github.com/CryZe/livesplit-urn/blob/9b2e109ad081827ed12afcfa1ebaf9f77905a27b/urn.c#L176](url) )

**Comment by CryZe** [comment]
Okay cool :)
