### ISSUE TITLE
bytearray needs an encoding in Python 3.6.2

### ISSUE THREAD

**Issue by stevensmedia** [CryZe/livesplit-core#68]
In the Python bindings, class Run.parse_file is doing a:

`bytes = bytearray(file.read())`

But it needs to pick an encoding, at least in my Python 3.6.2 just installed from python.org, such as:

`bytes = bytearray(file.read(), 'utf8')`

**Comment by CryZe** [comment]
Is that compatible with older versions too? If there's a way to support old versions too, feel free to fix it and do a PR.

**Comment by stevensmedia** [comment]
Looks like bytearray was added in 2.6 and had that argument all along. Will do the PR.

**Comment by CryZe** [comment]
Wait, why do you need an encoding for a byte array? That seems super weird O.o

**Comment by stevensmedia** [comment]
Good question.  So I have the real fix figured out.  I was slightly thrown off here by a subtle change in read() semantic porting my code from python 2 to python 3.

(Yes you may laugh from rust land :)

**Comment by stevensmedia** [comment]
PR #69 sent.
