### ISSUE TITLE
Delta Component Text doesn't match LiveSplit

### ISSUE THREAD

**Issue by CryZe** [CryZe/livesplit-core#75]
Looks like it can show just "Delta", which is not what LiveSplit does.

**Comment by hallcristobal** [comment]
https://github.com/CryZe/livesplit-core/blob/624b8ff398fc4ccd76438fc518ca3846aded93c3/src/component/delta.rs#L82-L91

Doesn't account for if the `comparison_override` isn't selected so just defaults to "Delta". Will fix today when I have a place to plug in my laptop 😬

**Comment by CryZe** [comment]
Keep in mind, that text is also used for the name in the layout editor, which apparently doesn't match the text shown on the component for this component, which is the actual reason for this bug (most other components do). So if you fix this, make sure that both of them are correct. Maybe we want a test to ensure this stays correct. I'm not sure, you decide.

**Comment by hallcristobal** [comment]
That commit works, however A) I'm not sure it's the prettiest/cleanest way and B) rustfmt-nightly refuses to install on my computer for some reason (I probably need to update rust itself) so formatting
