### ISSUE TITLE
Implement Balanced PB comparison and algorithm

### ISSUE THREAD

**Issue by wooferzfg** [CryZe/livesplit-core#82]

**Comment by CryZe** [comment]
I started implementing this and I encountered this: [Code](https://github.com/LiveSplit/LiveSplit/blob/0d9b6a9a9eb56b65d0e8e8a45d7510dee4fbdc17/LiveSplit/LiveSplit.Core/Model/Comparisons/PercentileComparisonGenerator.cs#L91-L93)
```c#
tempList = tempList.OrderBy(x => x.Value).ToList();
var totalWeight = tempList.Aggregate(0.0, (s, x) => (s + x.Key));
var smallestWeight = tempList[0].Key;
```

It sorts by the times (Value) in the list and then assumes the smallest weight (Key) is in the first slot, but I don't think that necessarily the case, as the weight isn't proportional to the time. Unless this means "the smallest time's weight".
